# Generated by Django 5.0.6 on 2024-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phantombuster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('cookie', models.CharField(max_length=300)),
                ('link_to_setup', models.CharField(max_length=300)),
                ('link_to_launch', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enable', models.BooleanField(default=True)),
                ('number_account', models.IntegerField()),
                ('error_limit', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='RelevanceAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain_credits', models.IntegerField()),
                ('project_id', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scrapin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain_credits', models.IntegerField()),
                ('api_key', models.CharField(max_length=100)),
            ],
        ),
    ]
