HTTP_ADDR = "0.0.0.0"
HTTP_PORT = "8080"
ENVIRONMENT = "LOCAL"
CONTEXT_PATH = "/cvseeker"
DB_MYSQL_USERNAME = "root"
DB_MYSQL_PASSWORD = "password"
DB_MYSQL_HOST = "127.0.0.1"
DB_MYSQL_PORT = 3306
DB_MYSQL_DATABASE = "TalentAcquisition"
DB_MYSQL_MAX_IDLE_CONNECTIONS = 5
DB_MYSQL_MAX_OPEN_CONNECTIONS = 5
DB_MYSQL_CONNECTION_MAX_LIFETIME = 300

API_DEFAULT_PAGE_SIZE = 10
API_MIN_PAGE_SIZE = 5
API_MAX_PAGE_SIZE = 100

FOLDER_TMP = "/tmp"

